### ISSUE TITLE
Add creditor address

### ISSUE THREAD

**Issue by pblanchardie** [inisos/bank4j#2]
@valh1996 requested in #1:

> Add address lines (not the structured ones) for the creditor

Do you mean adding `CdtTrfTxInf.Cdtr.PstlAdr`?
Could you elaborate "not the structured ones"?

A postal address is made of:

- AddressType <AdrTp> [0..1] Code
- Department <Dept> [0..1] Max70Text
- SubDepartment <SubDept> [0..1] Max70Text
- StreetName <StrtNm> [0..1] Max70Text
- BuildingNumber <BldgNb> [0..1] Max16Text
- PostCode <PstCd> [0..1] Max16Text
- TownName <TwnNm> [0..1] Max35Text
- CountrySubDivision <CtrySubDvsn> [0..1] Max35Text
- Country <Ctry> [0..1] CountryCode
- AddressLine <AdrLine> [0..7] Max70Text

**Comment by valh1996** [comment]
@pblanchardie Exactly, that's what I'm talking about.

Regarding "not the structured ones", I meant that I also need to be able to insert some address lines:
- `AddressLine [0..7] Max70Text`

Because in my case, the addresses I have are not necessarily complete: for some payments I only have the city, for example. But more specifically, all the addresses we have are address lines, not addresses structured by field (city, zip code, street, etc.).

If we don't have an address at all, can I just add a blank address line? Because this field is mandatory for our bank ([CIC](https://www.cic.ch/fr/))

___

Note aside, it would be great if this could be integrated by tomorrow as I have over 200 payments to launch by Thursday.
Sorry to ask this so quickly, I'm aware that it's open-source :/

Thanks for your work 🙏🏻 !

**Comment by valh1996** [comment]
@pblanchardie It's confirmed from the bank, it's possible to put address in the following format :
```
<Cdtr>
<Nm>DOE John</Nm>
  <PstlAdr>
    <Ctry>CH</Ctry>
    <AdrLine>Test Tester</AdrLine>
    <AdrLine>1228 Test Adress</AdrLine>
  </PstlAdr>
</Cdtr>
```

More from the upper PDF :

<img width="789" alt="CleanShot 2023-10-24 at 10 34 00@2x" src="https://github.com/inisos/bank4j/assets/20521112/9907a9c2-743e-480c-920c-3db71a8a48ba">

**Comment by pblanchardie** [comment]
@valh1996 ok, in progress, should be done quickly

**Comment by pblanchardie** [comment]
@valh1996 2.0.0 has been deployed to maven central, should be online soon
https://sbom.sonatype.com/report/T1-118f0f57da8c6b3097cc-406c4583dbca8-1698158325-67f48cafbf06433daf3317aba0029d23

Let's discuss on #4 if you want more information
