### ISSUE TITLE
Customize namespace

### ISSUE THREAD

**Issue by valh1996** [inisos/bank4j#5]
Hi @pblanchardie,

My bank tells me that the header is no longer recognized :
```xml
<?xml version="1.0" encoding="utf-8"?>
<Document xmlns="urn:iso:std:iso:20022:tech:xsd:pain.001.001.03">
```

He suggests this header which seems more appropriate:
```xml
<?xml version="1.0" encoding="utf-8"?>
<Document xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.six-interbank-clearing.com/de/pain.001.001.03.ch.02.xsd">
 ```
 
 Do you have any ideas on how we can customize this header to suit our needs?
 
 Thanks

**Comment by pblanchardie** [comment]
A quick workaround would be to replace the header on your side, after generation. Pretty easy because it's always the same, at the same place: line 2.
As your header is specific to your bank (and http://www.six-interbank-clearing.com/de/pain.001.001.03.ch.02.xsd is not available), it's the best thing to do now.

Using JAXB, there is no easy way to allow customization of the namespace URI.

I could also add a parameter that replaces the header after generation, but I won't be able to do it quickly and it's a hack that should be on the user side.

In the future, I may provide alternative implementations (JAXB2 is the current but you could choose bank4j-jackson or a custom implementation with no external dependency at all) and some would allow changing the namespace easily.

**Comment by valh1996** [comment]
Thank you for your quick response!
I'll use the workaround to replace de specific header using a regex in my generation script.
